# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'openmv.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(927, 564)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/12396/.designer/backup/1710225834150.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("background-color:#eeeeee;")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setEnabled(False)
        self.pushButton.setGeometry(QtCore.QRect(10, 240, 111, 51))
        self.pushButton.setStyleSheet("QPushButton{\n"
"    border-style:solid;\n"
"    border-width: 1px;\n"
"    border-radius:10px;\n"
"    border-color:#000000;\n"
"\n"
"    background-color:#ffe6fc;\n"
"\n"
"    color:#000000;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setEnabled(False)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 170, 111, 51))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    border-style:solid;\n"
"    border-width: 1px;\n"
"    border-radius:10px;\n"
"    border-color:#000000;\n"
"\n"
"    background-color:#ffe6fc;\n"
"\n"
"    color:#000000;\n"
"}")
        self.pushButton_2.setIconSize(QtCore.QSize(100, 100))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 100, 111, 51))
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"    border-style:solid;\n"
"    border-width: 1px;\n"
"    border-radius:10px;\n"
"    border-color:#000000;\n"
"\n"
"    background-color:#ffe6fc;\n"
"\n"
"    color:#000000;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(140, 100, 111, 22))
        self.comboBox.setStyleSheet("background-color:#ffffff")
        self.comboBox.setObjectName("comboBox")
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setEnabled(True)
        self.textBrowser.setGeometry(QtCore.QRect(260, 100, 661, 381))
        self.textBrowser.setStyleSheet("border-style:solid;\n"
"border-width: 1px;\n"
"border-radius:5px;\n"
"border-color:#000000;\n"
"\n"
"background-color:#f0fff3;\n"
"")
        self.textBrowser.setObjectName("textBrowser")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setEnabled(False)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 310, 111, 51))
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"    border-style:solid;\n"
"    border-width: 1px;\n"
"    border-radius:10px;\n"
"    border-color:#000000;\n"
"\n"
"    background-color:#ffe6fc;\n"
"\n"
"    color:#000000;\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.comboBox_2 = QtWidgets.QComboBox(Form)
        self.comboBox_2.setGeometry(QtCore.QRect(140, 310, 111, 22))
        self.comboBox_2.setStyleSheet("background-color:#ffffff")
        self.comboBox_2.setObjectName("comboBox_2")
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setEnabled(False)
        self.pushButton_5.setGeometry(QtCore.QRect(10, 380, 111, 51))
        self.pushButton_5.setStyleSheet("QPushButton{\n"
"    border-style:solid;\n"
"    border-width: 1px;\n"
"    border-radius:10px;\n"
"    border-color:#000000;\n"
"\n"
"    background-color:#ffe6fc;\n"
"\n"
"    color:#000000;\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.textBrowser_2 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_2.setEnabled(True)
        self.textBrowser_2.setGeometry(QtCore.QRect(-10, 0, 951, 91))
        self.textBrowser_2.setStyleSheet("border-style:solid;\n"
"border-width: 1px;\n"
"border-radius:5px;\n"
"border-color:#000000;\n"
"\n"
"background-color:#16b3d3;\n"
"")
        self.textBrowser_2.setObjectName("textBrowser_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "门禁系统"))
        self.pushButton.setText(_translate("Form", "添加用户"))
        self.pushButton_2.setText(_translate("Form", "查看门禁记录"))
        self.pushButton_3.setText(_translate("Form", "打开串口"))
        self.pushButton_4.setText(_translate("Form", "删除用户"))
        self.pushButton_5.setText(_translate("Form", "远程开锁"))
        self.textBrowser_2.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt; color:#ffffff;\">  智能</span><span style=\" font-size:18pt; color:#ffffff;\">门禁系统</span></p></body></html>"))

    def button_3_change(self, str):
        _translate = QtCore.QCoreApplication.translate
        self.pushButton_3.setText(_translate("Form", str))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
